[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[healthcheck]
path = "/health"
port = 8080

[[services]]
name = "fairydust-mcp"
targetPort = 8080